### ISSUE TITLE
This a test

### ISSUE THREAD

**Issue by zstumgoren** [associatedpress/datakit-core#19]
## Overview

This is a test ticket.

**Comment by zstumgoren** [comment]
@myersjustinc Howdy. I created this ticket yesterday for demo purposes in a class, but it seems I may not have the ability to delete it! Do you know if my owner/admin perms have been deprecated? Or perhaps the delete feature is so well hidden that I'm not finding it? Either way, feel free to delete this ticket and sorry for any confusion!

**Comment by myersjustinc** [comment]
None of us had permissions to do it, but [I just looked up how to add those permissions](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/allowing-people-to-delete-issues-in-your-organization), and now I have that option. (And so should you!) I'll delete now.
